### ISSUE TITLE
MB and CTS module todo

### ISSUE THREAD

**Issue by john-harrold** [john-harrold/ruminate#20]
Todo list for the MB and CTS modules:
- [x] MB_append_report() https://github.com/john-harrold/ruminate/commit/176ebacfdea31d68e72fff9810eea680f814960c
- [x] Add time unit selection to CTS: pass units through to the simulate_rules(), add time columns to outputs, add selection of time units to the plotting https://github.com/john-harrold/ruminate/commit/e1350a80bbce3ec52af86444b026e167ff0f8218
- [x] CTS_fetch_code() https://github.com/john-harrold/ruminate/commit/c6dfd3d6d545a307598e4f3e7979a367fa976100
- [x] CTS_append_report() https://github.com/john-harrold/ruminate/commit/2146ebbbb1f39f5b222997c9b8c6be9a3ff5ae73
- [x] MB: Fix reactivity in CTS when models in MB change https://github.com/john-harrold/ruminate/commit/24f0bdf084d976f0768db5540fc938ef61ebd37a
- [x] CTS: Figure out alignment of buttons and pull downs in the simres UI 
- [x] MB: Append model selection not updating https://github.com/john-harrold/ruminate/commit/612e64641e4fe977d19bd0c4d8c15688752e69b7
- [x] CTS: Report Preview/Interactive not working https://github.com/john-harrold/ruminate/commit/a037f6358c028153d5c481be8613f53e79f899c7
- [x] CTS: Changes to visit times not taking effect https://github.com/john-harrold/ruminate/commit/111aec750f087077100009631ddcbc578c8231bf
- [x] CTS: Simulate single subject seems to only recognize the first evaluation time https://github.com/john-harrold/ruminate/commit/d57b4c4e9432acab57aa46e800b080cbfc9e990e
- [x] CTS: Set seeds and confirm reproducibility https://github.com/john-harrold/ruminate/commit/d6a0c66131be209149bccb34697e07b864c91edf
- [x] MB: Add NONMEM and Monolix exports https://github.com/john-harrold/ruminate/commit/d6590cbd40535c19a8074d22afb95dc3458fa84a

**Comment by john-harrold** [comment]
MB: Fix reactivity in CTS when models in MB change: the updatePickerInput needs a req() for the id to be updated (ie req(input$source_model))
